import { Inter } from 'next/font/google'
import Link from "next/link";
import "../../style/global.css"


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
          <Link className='inline-block m-3 p-3' href="/">Home</Link>
          <br />
          <Link className='inline-block m-3 p-3' href="/about">About</Link>
          <br />
          <Link className='inline-block m-3 p-3' href="/user">User</Link>
        </div>
        {children}
        </body>
    </html>
  )
}
