import '../../node_modules/tailwindcss/';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function Home() {
  return (
    <>
      <div className='border w-full flex justify-center items-center font-semibold text-5xl mt-2'>
        Home page

      </div>
    </>
  )
}
